export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = "LOGOUT_USER";

export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_ERROR = "LOADING_ERROR";

export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";


export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS'

export const UPDATE_COLUMN_HIDDEN = 'UPDATE_COLUMN_HIDDEN'

export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const HANDLE_DATA_SUCCESS = "HANDLE_DATA_SUCCESS"

export const HANDLE_SEARCH_TO_REPORT = "HANDLE_SEARCH_TO_REPORT"

export const HANDLE_DATE_CHANGE = "HANDLE_DATE_CHANGE"
export const HANDLE_ELEMENT_SIZE = "HANDLE_ELEMENT_SIZE"
export const HANDLE_SCREEN_RESIZE = "HANDLE_SCREEN_RESIZE"

export const MANAGE_UPLOADS_SUCCESS = "MANAGE_UPLOADS_SUCCESS"
